### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by silverkorn** [olmokramer/atom-stylus-autocompile#1]
Requiring `$` from `atom` is no longer supported.
If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead:
  `{$} = require 'atom-space-pen-views'`
  or
  `$ = require 'jquery'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
Or add `"jquery": "^2"` to your package dependencies.

```
Object.Object.defineProperty.get (C:\Users\censored\Apps\Atom\0.190.0\resources\app\exports\atom.js:44:11)
Object.<anonymous> (C:\Users\censored\.atom\packages\stylus-autocompile\lib\stylus-autocompile-view.coffee:1:7)
```

**Comment by olmokramer** [comment]
Yeah, I've been meaning to update the packages (i.e. pull changes from [less-autocompile](https://atom.io/packages/less-autocompile) but I've been super busy for a while. I'll try to get to it somewhere this week.

Cheers,

**Comment by silverkorn** [comment]
No problem, great to see that you will do it when you'll have a chance.

**Comment by olmokramer** [comment]
Just released a new version that removes all the deprecations!

Cheers,

**Comment by silverkorn** [comment]
Alright! Updated and seems good.
Thank you!
