### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by ivteplo** [olmokramer/atom-stylus-autocompile#20]
Hello! I like stylus very much. But unfortunately this package doesn't work on my laptop. Maybe I do something wrong, so I need help. I write down the code in my `stylus/style.styl` file. I write:
`// out: ../css/style.css`
Do I write code not right or it is the package error? No errors or buttons like "Not compiled" I haven't got.

And one more question. Should I have installed stylus on laptop or not? (I use jade compiler without installing jade...)

Thank you.

**Comment by olmokramer** [comment]
Hi @ivteplo , I'm sorry for the extremely late reply. As you have probably noticed I've stopped maintaining my Atom plugins a few years ago. I got very frustrated with how Atom was maintained and started ignoring all of my plugins. I'm sorry for that. I won't install Atom to test and mergeer PRs, but I'd be happy to transfer my repositories to anyone that wants to maintain any of my plugins. Again, I'm sorry.
