### ISSUE TITLE
Stylus does not compile

### ISSUE THREAD

**Issue by fraxken** [olmokramer/atom-stylus-autocompile#3]
Everything is in the title, after some reebot of Atom .styl does not compile. (All .styl)
#### One of my header :

``` css
// out: ../../css/popup/popup.css, sourcemap: false, compress: true
```

I use the same settings everywhere.

**Comment by olmokramer** [comment]
Hi, thanks for the report. I'll look into this sometime tomorrow.

**Comment by olmokramer** [comment]
Hi, I'm sorry I got really busy over the last few weeks. It seems to work fine for me with the header you showed... Is header the first line in your file? That's currently required

**Comment by fraxken** [comment]
Yes the first line. I'm using multiple virtual machine. Just the package not work on one of them but work well for others Virtual machine. 

I do not understand at all. (PS : Same copy/paste environnement for all VM)

**Comment by olmokramer** [comment]
Hey, I just published an update of the package. The update includes better parsing of the parameter line, so I thought this may fix your issue as well.

**Comment by fraxken** [comment]
Hi, Good job ! I work with for several projects and this time no problem!

**Comment by olmokramer** [comment]
Ok, that's great! :) Closing this issue then
