### ISSUE TITLE
Imported .styl component needs to be saved twice to compile

### ISSUE THREAD

**Issue by simrobin** [olmokramer/atom-stylus-autocompile#6]
Hello,

I recently have discovered a problem with @imported .styl files, I thought I was the only one having this problem, but when I told my coworker to update the package (for the nib feature), they experienced the same problem.

When you are working on an @imported .styl file referencing to a main .styl file, you need to save the file twice in order to compile.

Step to reproduce : 
- Create main.styl and component.styl files in the same directory

main.styl : 

```
 // out: main.css

@import 'component.styl';

body {
  margin: auto;
}
```

component.styl :

```
 // main: main.styl
```
- add stylus block to component.styl : 

```
 // main: main.styl

.my-class {
  display: none;
}
```
- save the file component.styl
- check main.css generated file (no change)
- save the file component.styl
- check again main.css (the new css property should be there now)

I'll try to look at it this week to see if I can find a clue.

**Comment by olmokramer** [comment]
Hmm, maybe this happens because the stylus compilation is started before the file is actually saved to disk?   I can't test right now, but can you try to wrap a `process.nextTick(function() { ... })` around the `handleSave` function?

**Comment by simrobin** [comment]
Ok I'll test it today and I'll let you know !
Thanks for the quick reply.

**Comment by simrobin** [comment]
Ok, my bad, it seems to be working since 0.3.1 due to commit https://github.com/olmokramer/atom-stylus-autocompile/commit/a6181dcb298c703ad5dd283517316a19dea6beed
We updated and we are fine now.
It's amazing when issues are solved before we found them !

**Comment by olmokramer** [comment]
> It's amazing when issues are solved before we found them

Haha yeah I love it when that happens! Either as a user or a maintainer :D
