### ISSUE TITLE
Inconsistent sourcemap comment if source and destination have different names

### ISSUE THREAD

**Issue by pasqLisena** [olmokramer/atom-stylus-autocompile#7]
I have this source file:

```
input.styl
```

I set in output (and I obtain):

```
output.css
output.css.map
```

But the last line of the css file is:

```
/*# sourceMappingURL=input.css.map */
```

This prevent the browsing to find the correct file.

**Comment by olmokramer** [comment]
Should be fixed as of v0.4.0 :)
