### ISSUE TITLE
Annoying compilation success message

### ISSUE THREAD

**Issue by pasqLisena** [olmokramer/atom-stylus-autocompile#9]
I find a little annoying the green success message that appears on top right every time I save the file. I'm not the only one (this project has a [fork](https://github.com/Dinius/dini-atom-stylus-autocompile/commit/0b03d7eeaad58cdc7467b59c9521661e8243d6f6) in which the messages are removed).

I think we can keep the error messages as they are, while have a small flag on the bottom of the screen as in [jade-autocompile](https://github.com/ManRueda/jade-autocompile) (see screenshot).

![image](https://cloud.githubusercontent.com/assets/4126222/12350423/430843ac-bb77-11e5-92e4-85ce04a99886.png)

**Comment by ghost** [comment]
same here

**Comment by olmokramer** [comment]
Yeah I agree, the messages are quite annoying. I'll see what I can do (probably just copy some stuff from the package you mentioned :p)

**Comment by olmokramer** [comment]
I just published a new version that removes the annoying messages. It has a message in the status bar similar to jade-autocompile that shows the number of output files and the number of errors.

![stylus-autocompile-status-bar-message](https://cloud.githubusercontent.com/assets/3612514/12964631/7b45d36c-d051-11e5-8744-8d61d287256f.png)

You can click on it to show the list of output files in a notification in the upper right corner.

![stylus-autocompile-output-notification](https://cloud.githubusercontent.com/assets/3612514/12964632/80094e06-d051-11e5-96b3-f49ac108b56a.png)

The error messages are still the same.

Let me know what you think! :)

**Comment by ghost** [comment]
Awesome. Can you make the same at your other project atom-coffee-autocompile?

**Comment by pasqLisena** [comment]
This is a very good solution, elegant and practical.
Thank you very much :smile:

**Comment by olmokramer** [comment]
@rvr-psychonaut I've just updated coffee-autocompile to use the same messages :)
